Boorunaut/Boorunaut

- account/admin.py
- account/apps.py
- account/forms.py
- account/models.py
- account/templates/account/sign_in.html
- account/tests.py
- account/urls.py
- account/views.py
- booru/models.py
- booru/templates/booru/menu.html
- booru/utils.py
- boorunaut/settings.py
- boorunaut/urls.py
Creates the model Account and changes the default user model to it on settings.py .
> Changing the user model from User to Account

- booru/templates/booru/posts.html
- booru/urls.py
- booru/views.py
Adds pagination to the posts list in the end of the page.
> Frontpage pagination

- account/forms.py
- account/templates/account/login.html
- account/templates/account/register.html
- account/views.py
- booru/forms.py
- booru/models.py
- booru/templates/booru/alias_create.html
- booru/templates/booru/alias_detail.html
- booru/templates/booru/alias_list.html
- booru/templates/booru/base_index.html
- booru/templates/booru/implication_create.html
- booru/templates/booru/implication_detail.html
- booru/templates/booru/implication_list.html
- booru/templates/booru/index.html
- booru/templates/booru/navbar.html
- booru/templates/booru/post_detail.html
- booru/templates/booru/posts.html
- booru/templates/booru/tag_edit.html
- booru/templates/booru/tag_list.html
- booru/templates/booru/upload.html
- booru/views.py
* Created **UserAuthenticationForm**, a Form that inherits from **AuthenticationForm** and have additions to allow bootstrap styling modifications;
* Created **UniqueUsernameField** for the **UserAuthenticationForm** in order to validate if the given username is in the database, so if a visitor is trying to log in to a inexistent account, it will receive a field error;
* Removed all unnecessary margin;
* Extracted all forms widgets (that were possible) from the fields declaration in order to maintain a more clear code;
* Remove all navbar duplication.
> Added bootstrap classes to some forms and fixed visual errors.

- booru/forms.py
EditPostForm's widgets were written in the incorrect form, so it was being ignored.
> Fixed EditPostForm's widgets.

- booru/forms.py
- booru/models.py
- booru/static/booru/css/post_detail.css
- booru/templates/booru/post_detail.html
- booru/templatetags/number_converter.py
- boorunaut/settings.py
Makes some quality of life changes on the Post Detail page and fixes a bug where the edit form didn't work.
It changes the sidebar to use tables and custom CSS, changes the edit form to a better position and with correct widgets, adds better number notations on the tag count of the sidebar, and etc.
The issues explain the other changes...
> Post detail visual changes

- booru/forms.py
- booru/templates/booru/post_detail.html
- booru/views.py
Some commits went missing on PR #30...
> Continuing PR #30

- booru/tests/tests_booru_clients.py
- booru/tests/tests_booru_forms.py
This PR adds unit tests to forms and some integration tests on creating and listing posts.
Partially fixes #25.
> Adds some unit tests and integration tests.

- account/templates/account/login.html
- account/templates/account/profile.html
- account/templates/account/register.html
- booru/templates/booru/alias_create.html
- booru/templates/booru/alias_detail.html
- booru/templates/booru/alias_list.html
- booru/templates/booru/base.html
- booru/templates/booru/base_index.html
- booru/templates/booru/implication_create.html
- booru/templates/booru/implication_detail.html
- booru/templates/booru/implication_list.html
- booru/templates/booru/index.html
- booru/templates/booru/post_detail.html
- booru/templates/booru/posts.html
- booru/templates/booru/tag_edit.html
- booru/templates/booru/tag_list.html
- booru/templates/booru/upload.html
As it's often repeated across multiple htmls, the div 'container' was moved to the base html files.
The navbar 'margin bottom' was removed and it was added a 'margin top' with the same size to the 'container' in the bases files, in order to allow easy future customizations.
> Moved the main div container to be at the bases html

- booru/forms.py
- booru/models.py
- booru/templates/booru/base_admin.html
- booru/templates/booru/staff_mass_rename.html
- booru/urls.py
- booru/views.py
This tool is able to make staff members find and replace one or multiple tags by others. Fixes #49 .
> Creates tool Mass Rename on Staff.

- booru/templates/booru/post_detail.html
- booru/templates/booru/posts.html
- booru/views.py
This populates the list of tags on the left side of the post list.
> Adding common tags on the posts listing

- booru/models.py
- booru/templatetags/version_comparator.py
- booru/utils.py
This causes bugs because it is importing a system that is not included in the project anymore.
> Removing references the legacy history system

- booru/templates/booru/post_detail.html
- booru/views.py
> Adding image size to the Information section on posts.

- booru/templates/booru/index.html
Removes view counter on index.html that doesn't work.
> Removing unused view counter

- booru/templates/booru/index.html
- booru/templates/booru/post_detail.html
- setup.py
> Fixing column order on mobile for posts

- booru/views.py
> Fixes search on tags listing

- booru/forms.py
- booru/models.py
- booru/templates/booru/post_detail.html
This adds form validations for multiple URLs on the source field of posts. This also fixes the text-truncation on the sidebar that did not reveal the full URL. It also turns the source links into hyperlinks.
> Multiple URLs on source field and adding validations.

- booru/core/views.py
- booru/forms.py
- booru/setup/project_template/project_name/settings.py
- booru/templates/booru/account/profile.html
- booru/templates/booru/gallery_create.html
- booru/templates/booru/gallery_edit.html
- booru/templates/booru/gallery_list.html
- booru/templates/booru/implication_create.html
- booru/templates/booru/post_detail.html
- booru/templates/booru/staff_hash_ban.html
- booru/templates/booru/staff_mass_rename.html
- booru/templates/booru/staff_site_configuration.html
- booru/templates/booru/staff_user_tools.html
- booru/templates/booru/tag_edit.html
- booru/templates/booru/tag_list.html
- devproject/settings.py
- requirements.txt
Some field warnings were not working correctly, and this fixes it by using the automatic django-crispy-forms system.
> Adds django-crispy-forms to generate some forms

- booru/forms.py
- booru/models.py
- booru/templates/booru/implication_detail.html
- booru/templates/booru/implication_list.html
- booru/templates/booru/post_detail.html
- booru/templates/booru/tag_detail.html
- booru/templates/booru/tag_list.html
- booru/templates/booru/upload.html
- booru/tests/tests_booru_forms.py
This cleans the form of Implication creation by making the tags lowercase. (Fixes #116 )
This also changes the form of Aliases to include instructions to create new aliases. (Fixes #117 )
Finally, this changes some of the visuals for detailing implications and seeing aliases, by adding colors and URLs to them.
> Fixes bug with uppercase implications, changes Alias form and better visuals.

- booru/context_processors.py
- booru/core/migrations/0001_initial.py
- booru/forms.py
- booru/setup/project_template/project_name/settings.py
- booru/templates/booru/base.html
- booru/templates/booru/base_index.html
- booru/views.py
- devproject/settings.py
Adds a field on site configuration to customize the site description. (The one that appears in searche engines)
> Adding site description

- booru/models.py
- booru/utils.py
- requirements.txt
This refactors the system that generates thumbnails and sample images to use built-in `thumbnail` function from the Pillow library instead of the current over complicated method.
> Refactoring thumbnailing and sampling system
